language: python

dist: xenial

cache: pip

python:
    - "3.6"
    - "3.7"

env:
    - TEST_DATABASE_URLS="postgresql://localhost/test_database, mysql://localhost/test_database, sqlite:///test.db"

services:
    - postgresql
    - mysql

before_install:
    - sudo apt-get update
    - sudo apt-get install unixodbc-dev

install:
    - pip install -U -r requirements.txt

before_script:
    - psql -c 'create database test_database;' -U postgres
    - echo 'create database test_database;' | mysql

script:
    - scripts/test

after_script:
    - codecov
